export const techniques = [
  {
    id: 1,
    title: "Drip Irrigation System",
    slug: "drip-irrigation-system",
    added_by: 3,
    impact: "high",
    region: [
      {
        id: 5,
        name: "Maharashtra",
      },
      {
        id: 7,
        name: "Gujarat",
      },
    ],
    categories: [
      {
        id: 1,
        name: "Agriculture",
        description: "Techniques and methods for agricultural water conservation.",
      },
      {
        id: 2,
        name: "Irrigation",
        description: "Methods to efficiently deliver water to plants and crops.",
      },
    ],
    summary:
      "A water-efficient irrigation method that delivers water directly to plant roots, minimizing evaporation and runoff.",
    detailed_content:
      "Drip irrigation is a type of micro-irrigation system that saves water and nutrients by allowing water to drip slowly to the roots of plants, either from above the soil surface or buried below the surface. The goal is to place water directly into the root zone and minimize evaporation. Water and nutrients are delivered continuously in small amounts, creating optimal growing conditions. Drip irrigation systems use 30-50% less water than conventional irrigation methods, making them ideal for areas with water scarcity.",
    benefits: [
      "Reduces water usage by up to 60% compared to traditional irrigation",
      "Minimizes soil erosion and nutrient runoff",
      "Decreases weed growth by limiting water to plant roots",
      "Can be automated for optimal water delivery timing",
      "Reduces labor costs for watering and maintenance",
    ],
    materials: [
      "Drip tubing or tape",
      "Pressure regulator",
      "Filter",
      "Connectors and fittings",
      "Timer (optional)",
      "Backflow preventer",
    ],
    steps: [
      "Design your system based on your garden layout and water source",
      "Install a backflow preventer and pressure regulator at your water source",
      "Connect the main water line to your garden area",
      "Lay out drip lines along plant rows",
      "Install emitters at each plant location",
      "Test the system and adjust water flow as needed",
      "Add a timer for automated watering (optional)",
    ],
    main_image: "https://cdn11.bigcommerce.com/s-tjrce8etun/product_images/uploaded_images/drip-lines-in-garden.jpg",
    created_on: "2025-03-16T10:48:13.336621Z",
    updated_on: "2025-03-16T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 2,
        image: "https://www.rainbird.com/sites/default/files/inline-images/stakedrippers544_650x434_0.jpg",
        caption: "Drip irrigation system in a vegetable garden",
        order: 0,
        type: "other",
      },
      {
        id: 3,
        image: "https://cdn.wikifarmer.com/images/detailed/2023/04/Components-and-types-of-drip-irrigation.jpg",
        caption: "Close-up of drip emitters",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 2,
    title: "Rainwater Harvesting",
    slug: "rainwater-harvesting",
    added_by: 5,
    impact: "high",
    region: [
      {
        id: 8,
        name: "Rajasthan",
      },
    ],
    categories: [
      {
        id: 3,
        name: "Household",
        description: "Water conservation techniques for residential use.",
      },
      {
        id: 4,
        name: "Conservation",
        description: "Methods to preserve and protect water resources.",
      },
    ],
    summary: "Collecting and storing rainwater from rooftops for later use in gardens and households.",
    detailed_content:
      "Rainwater harvesting is the collection and storage of rain for reuse on-site, rather than allowing it to run off. Rainwater can be collected from roofs and redirected to a tank, cistern, deep pit, or aquifer. It can be used for various purposes including gardening, irrigation, and even indoor use with proper treatment. This technique is particularly valuable in arid regions or areas with seasonal rainfall patterns, providing water during dry periods and reducing demand on municipal water supplies.",
    benefits: [
      "Reduces demand on municipal water supply",
      "Lowers water bills",
      "Provides water during restrictions or drought",
      "Decreases stormwater runoff and erosion",
      "Helps recharge groundwater when properly designed",
    ],
    materials: [
      "Rain barrels or storage tanks",
      "Gutters and downspouts",
      "First-flush diverter",
      "Mesh screen (to filter debris)",
      "Spigot or pump for water access",
      "Overflow outlet",
    ],
    steps: [
      "Choose a suitable location for your rain barrel or tank",
      "Install or modify gutters to direct water to your collection point",
      "Add a first-flush diverter to remove initial contaminants",
      "Install a mesh screen to keep out debris and mosquitoes",
      "Connect the downspout to your storage container",
      "Add an overflow outlet for heavy rainfall events",
      "Install a spigot or pump for accessing the collected water",
    ],
    main_image: "https://nexteel.in/wp-content/uploads/2024/06/rainwater-harvesting-in-india.jpg",
    created_on: "2025-03-15T09:30:22.336621Z",
    updated_on: "2025-03-15T11:20:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 4,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Rooftop rainwater collection system",
        order: 0,
        type: "other",
      },
      {
        id: 5,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Underground rainwater storage tank",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 3,
    title: "Greywater Recycling",
    slug: "greywater-recycling",
    added_by: 2,
    impact: "medium",
    region: [
      {
        id: 9,
        name: "Karnataka",
      },
    ],
    categories: [
      {
        id: 3,
        name: "Household",
        description: "Water conservation techniques for residential use.",
      },
      {
        id: 5,
        name: "Recycling",
        description: "Methods to reuse water that would otherwise be wasted.",
      },
    ],
    summary: "Reusing household wastewater from sinks, showers, and laundry for irrigation.",
    detailed_content:
      "Greywater recycling involves capturing and treating water from bathroom sinks, showers, tubs, and washing machines for reuse in irrigation. This water contains fewer contaminants than blackwater (from toilets) and can be safely used for non-potable purposes with minimal treatment. By implementing a greywater system, households can significantly reduce their water consumption and make use of water that would otherwise go to waste. It's important to use plant-friendly, biodegradable soaps and detergents when implementing a greywater system.",
    benefits: [
      "Reduces household water consumption by up to 30%",
      "Decreases strain on septic systems",
      "Lowers water and sewage bills",
      "Reclaims valuable nutrients for plants",
      "Reduces the environmental impact of wastewater",
    ],
    materials: [
      "Diverter valves for plumbing",
      "Storage tank (optional)",
      "Basic filtration system",
      "Distribution pipes or hoses",
      "Plant-friendly soaps and detergents",
    ],
    steps: [
      "Check local regulations regarding greywater systems",
      "Install diverter valves on drains from sinks, showers, or washing machines",
      "Set up a simple filtration system to remove hair and particles",
      "Create a distribution system to your garden",
      "Use plant-friendly, biodegradable soaps and detergents",
      "Rotate watering areas to prevent soil saturation",
    ],
    main_image: "https://www.cleantechwater.co.in/wp-content/uploads/2019/08/Greywater-Recycling-Systems.jpeg",
    created_on: "2025-03-14T14:48:13.336621Z",
    updated_on: "2025-03-14T16:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 6,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Simple greywater diversion system",
        order: 0,
        type: "other",
      },
      {
        id: 7,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Garden irrigated with greywater",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 4,
    title: "Mulching Technique",
    slug: "mulching-technique",
    added_by: 7,
    impact: "medium",
    region: [
      {
        id: 7,
        name: "Gujarat",
      },
    ],
    categories: [
      {
        id: 1,
        name: "Agriculture",
        description: "Techniques and methods for agricultural water conservation.",
      },
      {
        id: 6,
        name: "Gardening",
        description: "Water-saving methods for garden maintenance.",
      },
    ],
    summary: "Applying organic material to soil surface to reduce evaporation and retain moisture.",
    detailed_content:
      "Mulching is the process of covering the soil surface with organic or inorganic materials to conserve soil moisture, improve soil health, reduce weed growth, and enhance the visual appeal of the area. Organic mulches like straw, wood chips, or compost break down over time, adding nutrients to the soil. This technique creates a protective layer that reduces water evaporation, regulates soil temperature, and prevents erosion. Mulching is one of the simplest yet most effective water conservation techniques for gardens and agricultural fields.",
    benefits: [
      "Reduces water evaporation by up to 70%",
      "Suppresses weed growth",
      "Regulates soil temperature",
      "Prevents soil erosion and compaction",
      "Adds nutrients to soil as organic mulches decompose",
    ],
    materials: ["Organic mulch (straw, wood chips, leaves, compost)", "Rake or shovel", "Wheelbarrow", "Garden gloves"],
    steps: [
      "Clear the area of weeds and debris",
      "Water the soil thoroughly before applying mulch",
      "Apply a 2-4 inch layer of mulch around plants",
      "Keep mulch a few inches away from plant stems to prevent rot",
      "Replenish mulch as it decomposes or blows away",
      "Mix old mulch into the soil periodically to add nutrients",
    ],
    main_image: "https://i.ibb.co/XZS9JhDb/Mulching-Technique.webp",
    created_on: "2025-03-13T10:48:13.336621Z",
    updated_on: "2025-03-13T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 8,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Garden bed with mulch application",
        order: 0,
        type: "other",
      },
      {
        id: 9,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Different types of organic mulch materials",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 5,
    title: "Contour Farming",
    slug: "contour-farming",
    added_by: 4,
    impact: "high",
    region: [
      {
        id: 10,
        name: "Madhya Pradesh",
      },
    ],
    categories: [
      {
        id: 1,
        name: "Agriculture",
        description: "Techniques and methods for agricultural water conservation.",
      },
      {
        id: 4,
        name: "Conservation",
        description: "Methods to preserve and protect water resources.",
      },
    ],
    summary: "Plowing and planting across slopes following their elevation contour lines to prevent runoff.",
    detailed_content:
      "Contour farming is the practice of plowing and planting across a slope following its elevation contour lines. These contour lines create a water break which reduces soil erosion and allows more time for water to settle into the soil, increasing water retention and reducing runoff. This technique is particularly effective in hilly or sloped agricultural areas where water runoff can be a significant problem. By creating these natural barriers to water flow, farmers can improve crop yields while conserving water and preventing soil loss.",
    benefits: [
      "Reduces soil erosion by up to 50%",
      "Increases water infiltration into soil",
      "Prevents nutrient runoff",
      "Improves crop yields in sloped areas",
      "Reduces flooding in lower areas",
    ],
    materials: [
      "A-frame level or water level",
      "Stakes or markers",
      "String or rope",
      "Plow or tiller",
      "Measuring tape",
    ],
    steps: [
      "Identify the slope direction on your land",
      "Use an A-frame level to mark contour lines across the slope",
      "Place stakes along these contour lines",
      "Plow or till along the marked contour lines",
      "Plant crops in rows following these contours",
      "Maintain contour integrity during cultivation",
    ],
    main_image: "https://i.ibb.co/8RkJ1P7/6d3ecf2c8d.jpg",
    created_on: "2025-03-12T10:48:13.336621Z",
    updated_on: "2025-03-12T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 10,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Aerial view of contour farming on hillside",
        order: 0,
        type: "other",
      },
      {
        id: 11,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Using A-frame level to mark contour lines",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 6,
    title: "Rooftop Gardening",
    slug: "rooftop-gardening",
    added_by: 6,
    impact: "medium",
    region: [
      {
        id: 11,
        name: "Delhi",
      },
    ],
    categories: [
      {
        id: 7,
        name: "Urban",
        description: "Water conservation techniques for urban environments.",
      },
      {
        id: 6,
        name: "Gardening",
        description: "Water-saving methods for garden maintenance.",
      },
    ],
    summary: "Creating gardens on rooftops to utilize rainwater and reduce urban heat island effect.",
    detailed_content:
      "Rooftop gardening involves creating green spaces on building rooftops. These gardens capture rainwater that would otherwise run off, while also providing insulation, reducing the urban heat island effect, and creating additional green space in urban areas. They can be designed for food production or purely aesthetic purposes. Rooftop gardens can be implemented on various scales, from simple container gardens to elaborate green roof systems with specialized layers for drainage, water retention, and plant support.",
    benefits: [
      "Captures and utilizes rainwater directly",
      "Reduces building cooling costs",
      "Decreases stormwater runoff in urban areas",
      "Creates habitat for pollinators",
      "Can provide fresh produce in urban settings",
    ],
    materials: [
      "Waterproof membrane",
      "Drainage layer",
      "Lightweight growing medium",
      "Containers or raised beds",
      "Drought-resistant plants",
      "Irrigation system (optional)",
    ],
    steps: [
      "Ensure your roof can support the additional weight",
      "Install a waterproof membrane to protect the roof structure",
      "Add a drainage layer to prevent water logging",
      "Install raised beds or containers with lightweight soil mix",
      "Plant drought-resistant species to minimize water needs",
      "Set up a simple irrigation system or water collection method",
    ],
    main_image: "https://i.ibb.co/FkhFjg3f/1568269103amazing-ways-to-design-house-rooftop-at-home.jpg",
    created_on: "2025-03-11T10:48:13.336621Z",
    updated_on: "2025-03-11T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 12,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Urban rooftop garden with vegetables",
        order: 0,
        type: "other",
      },
      {
        id: 13,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Rooftop garden drainage system installation",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 7,
    title: "Check Dams",
    slug: "check-dams",
    added_by: 8,
    impact: "high",
    region: [
      {
        id: 12,
        name: "Tamil Nadu",
      },
    ],
    categories: [
      {
        id: 4,
        name: "Conservation",
        description: "Methods to preserve and protect water resources.",
      },
      {
        id: 8,
        name: "Community",
        description: "Water conservation projects implemented at community level.",
      },
    ],
    summary: "Small barriers built across water channels to slow flow and prevent soil erosion.",
    detailed_content:
      "Check dams are small barriers constructed across water channels or drainage ditches to slow water flow and trap sediment. They reduce erosion, increase water infiltration into the soil, and help recharge groundwater. These structures are particularly effective in gullies or small streams with seasonal flow. Check dams can be constructed using local materials like stones, rocks, or even sandbags, making them an accessible solution for rural communities.",
    benefits: [
      "Slows water flow during heavy rainfall",
      "Reduces soil erosion in water channels",
      "Increases groundwater recharge",
      "Creates small water reservoirs for local use",
      "Relatively inexpensive to construct",
    ],
    materials: [
      "Stones or rocks of various sizes",
      "Cement (optional)",
      "Sand and gravel",
      "Wooden stakes",
      "Digging tools",
    ],
    steps: [
      "Identify appropriate locations in water channels",
      "Clear the area of debris and loose soil",
      "Dig a shallow trench across the channel for the foundation",
      "Place larger rocks at the bottom and sides for stability",
      "Build up the dam with progressively smaller stones",
      "Ensure the center is lower than the sides to direct water flow",
      "Reinforce with cement mortar for permanence (optional)",
    ],
    main_image: "https://i.ibb.co/LzxVsYkL/097d5d1f86.jpg",
    created_on: "2025-03-10T10:48:13.336621Z",
    updated_on: "2025-03-10T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 14,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Stone check dam in a seasonal stream",
        order: 0,
        type: "other",
      },
      {
        id: 15,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Check dam during monsoon season",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 8,
    title: "Fog Water Collection",
    slug: "fog-water-collection",
    added_by: 3,
    impact: "medium",
    region: [
      {
        id: 13,
        name: "Western Ghats",
      },
    ],
    categories: [
      {
        id: 9,
        name: "Innovation",
        description: "Innovative approaches to water collection and conservation.",
      },
      {
        id: 8,
        name: "Community",
        description: "Water conservation projects implemented at community level.",
      },
    ],
    summary: "Using mesh nets to capture water droplets from fog in arid coastal regions.",
    detailed_content:
      "Fog water collection uses large mesh nets to capture water droplets from fog, particularly in arid coastal regions where fog is common. As fog passes through the mesh, water droplets collect on the surface and drip down into collection troughs. This technique can provide a significant water source in areas with limited rainfall but frequent fog. The collected water can be used for drinking (after treatment), irrigation, or other purposes, providing a sustainable water source in challenging environments.",
    benefits: [
      "Provides water in arid regions with frequent fog",
      "Requires no energy input",
      "Low maintenance once installed",
      "Can supply water for drinking (with treatment) or irrigation",
      "Environmentally friendly water source",
    ],
    materials: [
      "Polypropylene mesh (Raschel net)",
      "Support poles (wooden or metal)",
      "Collection troughs",
      "Storage tank",
      "Pipes for water transport",
      "Anchoring materials",
    ],
    steps: [
      "Identify a suitable location with frequent fog and good airflow",
      "Install support poles securely in the ground",
      "Stretch mesh netting between poles, perpendicular to fog flow",
      "Attach collection troughs at the bottom of the mesh",
      "Connect troughs to storage tanks via pipes",
      "Add filtration system if water will be used for drinking",
      "Regularly inspect and repair mesh as needed",
    ],
    main_image: "https://i.ibb.co/JWg2V73t/Fog-water-collection-systems-Credit-Aqualonis.png",
    created_on: "2025-03-09T10:48:13.336621Z",
    updated_on: "2025-03-09T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 16,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Fog collection nets installed on hillside",
        order: 0,
        type: "other",
      },
      {
        id: 17,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Water droplets forming on mesh net",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 9,
    title: "Permeable Pavements",
    slug: "permeable-pavements",
    added_by: 5,
    impact: "medium",
    region: [
      {
        id: 14,
        name: "Kerala",
      },
    ],
    categories: [
      {
        id: 7,
        name: "Urban",
        description: "Water conservation techniques for urban environments.",
      },
      {
        id: 9,
        name: "Innovation",
        description: "Innovative approaches to water collection and conservation.",
      },
    ],
    summary: "Porous surfaces that allow rainwater to infiltrate into the ground rather than run off.",
    detailed_content:
      "Permeable pavements are designed to allow rainwater to pass through the surface and infiltrate into the ground below, rather than running off into storm drains. These surfaces can be made from various materials including pervious concrete, porous asphalt, or interlocking pavers with gaps filled with permeable material. By allowing water to percolate through to the soil beneath, permeable pavements help recharge groundwater, reduce flooding, and filter pollutants from rainwater. They are particularly valuable in urban areas with extensive paved surfaces.",
    benefits: [
      "Reduces stormwater runoff by up to 90%",
      "Recharges groundwater naturally",
      "Filters pollutants from rainwater",
      "Reduces flooding and erosion",
      "Can eliminate need for separate drainage systems",
    ],
    materials: [
      "Permeable pavers, pervious concrete, or porous asphalt",
      "Crushed stone aggregate base",
      "Geotextile fabric",
      "Edge restraints",
      "Leveling tools",
      "Compaction equipment",
    ],
    steps: [
      "Excavate the area to required depth (typically 8-12 inches)",
      "Line the excavation with geotextile fabric to prevent soil migration",
      "Add a layer of crushed stone aggregate as a base",
      "Compact the base layer appropriately",
      "Install edge restraints to prevent lateral movement",
      "Place permeable pavers or pour pervious concrete/asphalt",
      "Fill joints with small aggregate if using pavers",
      "Avoid sealing or using fine materials that could clog pores",
    ],
    main_image: "https://i.ibb.co/NnYND1KM/section-permeable-pavement-technical-sustainable-urban-design-theme-image-369046792.webp",
    created_on: "2025-03-08T10:48:13.336621Z",
    updated_on: "2025-03-08T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 18,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Permeable paver installation in urban setting",
        order: 0,
        type: "other",
      },
      {
        id: 19,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Cross-section of permeable pavement system",
        order: 1,
        type: "other",
      },
    ],
  },
  {
    id: 10,
    title: "Keyhole Garden",
    slug: "keyhole-garden",
    added_by: 7,
    impact: "medium",
    region: [
      {
        id: 8,
        name: "Rajasthan",
      },
    ],
    categories: [
      {
        id: 6,
        name: "Gardening",
        description: "Water-saving methods for garden maintenance.",
      },
      {
        id: 9,
        name: "Innovation",
        description: "Innovative approaches to water collection and conservation.",
      },
    ],
    summary: "Raised circular garden beds with a central compost basket for efficient water use.",
    detailed_content:
      "A keyhole garden is a raised, circular garden bed with a central compost basket that resembles a keyhole when viewed from above. This design allows for efficient water use as water and nutrients from the compost basket spread throughout the garden bed. It's particularly effective in arid regions and requires minimal irrigation. The central basket is used for adding kitchen scraps, greywater, and other compostable materials, which decompose and release nutrients directly to the surrounding plants, while also helping to retain moisture in the soil.",
    benefits: [
      "Reduces water usage by up to 70% compared to conventional gardens",
      "Recycles kitchen waste through the central compost basket",
      "Provides nutrients directly to plants",
      "Accessible design for those with limited mobility",
      "Works well in arid conditions",
    ],
    materials: [
      "Stones, bricks, or other materials for the circular wall",
      "Wire mesh or basket for the central compost area",
      "Cardboard or newspaper for the base layer",
      "Compost and soil mix",
      "Mulch material",
      "Various plant seedlings",
    ],
    steps: [
      "Mark a circle approximately 6 feet in diameter with a keyhole-shaped indentation",
      "Build a wall around the perimeter about 3 feet high",
      "Create a central basket with wire mesh in the center",
      "Layer the base with cardboard or newspaper to suppress weeds",
      "Add layers of compost, soil, and organic matter, sloping from center outward",
      "Plant vegetables and herbs, with those needing more water near the center",
      "Add kitchen scraps and water to the central basket regularly",
      "Mulch the surface to reduce evaporation",
    ],
    main_image: "https://i.ibb.co/Kc3b1S7F/VT17707-6x6-Keyhole-Mezza-Hero-2844x1899-52467ce2-d484-4776-98b7-0e261b70f906-1200x.webp",
    created_on: "2025-03-07T10:48:13.336621Z",
    updated_on: "2025-03-07T10:50:51.884280Z",
    is_published: true,
    likes: [],
    images: [
      {
        id: 20,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Keyhole garden with vegetables growing",
        order: 0,
        type: "other",
      },
      {
        id: 21,
        image: "/placeholder.svg?height=400&width=600",
        caption: "Central compost basket in keyhole garden",
        order: 1,
        type: "other",
      },
    ],
  },
]
