# Generated by Django 5.1.6 on 2025-05-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalwiki_app', '0004_forumtag_forumthread_forumcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumthread',
            options={},
        ),
        migrations.AddField(
            model_name='forumthread',
            name='type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('resource', 'Resource'), ('announcement', 'Announcement')], db_index=True, default='discussion', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='last_activity_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
