# Generated by Django 5.1.6 on 2025-05-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jalwiki_app', '0005_alter_forumthread_options_forumthread_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='TKIET College', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Warananagar', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, default='9876543210', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(default='416113', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
    ]
